###### DEV PIPELINE ######
image: docker:28.2.2
services:
  - name: docker:28.2.2-dind
    command: [ "--tls=false", "--mtu=1240" ]
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  TARGETPLATFORMS: "linux/amd64,linux/arm64"

stages:
  - build
#  - deploy

before_script:
  # Show Docker info (helpful for debugging)
  - docker info
  # Register QEMU emulation for cross-building
  - docker run --privileged --rm tonistiigi/binfmt --install all
  # Create and switch to a new Buildx builder
  - docker buildx create --name multiarch --driver docker-container --bootstrap
  - docker buildx use multiarch

build_docker_image_base_dev:
  stage: build
  only:
    - deploy/base
  script:
    - docker login $REGISTRY_URL -u "$BASE_REGISTRY_USERNAME" -p "$BASE_REGISTRY_PASSWORD"
    - docker buildx build --platform $TARGETPLATFORMS -t $REGISTRY_URL/$BASE_REGISTRY_PROJECT/access-management-api:$CI_PIPELINE_ID --push .

build_docker_image_base_temp_dev:
  stage: build
  only:
    - deploy-temp
  script:
    - docker login $REGISTRY_URL -u "$BASE_REGISTRY_USERNAME" -p "$BASE_REGISTRY_PASSWORD"
    - docker build -f Dockerfile_temp -t $REGISTRY_URL/$BASE_REGISTRY_PROJECT/access-management-api:$CI_PIPELINE_ID .
    - docker tag $REGISTRY_URL/$BASE_REGISTRY_PROJECT/access-management-api:$CI_PIPELINE_ID $REGISTRY_URL/$BASE_REGISTRY_PROJECT/access-management-api:latest
    - docker push $REGISTRY_URL/$BASE_REGISTRY_PROJECT/access-management-api:$CI_PIPELINE_ID
    - docker push $REGISTRY_URL/$BASE_REGISTRY_PROJECT/access-management-api:latest

build_docker_image_inss_dev:
  stage: build
  only:
    - deploy-inss
  script:
    - docker login $REGISTRY_URL -u "$REGISTRY_USERNAME" -p "$REGISTRY_PASSWORD"
    - docker buildx build --platform $TARGETPLATFORMS -t $REGISTRY_URL/$REGISTRY_PROJECT/access-management-api-dev:$CI_PIPELINE_ID --push .
