# General
spring.config.import=optional:file:.env[.properties]

server.port=${SERVICE_PORT:8080}

# Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_JWT_ISSUER}

# Datasource
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_INTERNAL_PORT}/${POSTGRES_DATABASE}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Entity Revision
# Track entity names modified during revision
#spring.jpa.properties.org.hibernate.envers.track_entities_changed_in_revision=true
# Enable withModifiedFlag globally
#spring.jpa.properties.org.hibernate.envers.global_with_modified_flag=true
# Set schema and catalog for audit tables
#spring.jpa.properties.org.hibernate.envers.default_schema=audit_schema

# Documentation
springdoc.swagger-ui.enabled=${ENABLE_SWAGGER:true}
springdoc.swagger-ui.operationsSorter=method

# Email Configuration
spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=IGRP.Notification@gov.cv
spring.mail.password=C@boverde25
spring.mail.properties.sender-id=iam@igrp.cv

# Minio
igrp.minio.url=${MINIO_URL}
igrp.minio.port=${MINIO_PORT}
igrp.minio.security=${MINIO_SECURITY}
igrp.minio.access-key=${MINIO_ACCESS_KEY}
igrp.minio.secret-key=${MINIO_SECRET_KEY}
igrp.minio.bucket-name=${MINIO_BUCKET_NAME}
igrp.minio.expiration-time=${MINIO_PRESIGNED_URL_EXPIRATION_TIME:60}

# Observability
#management.info.git.mode=full
#management.endpoints.web.exposure.include=*
#management.metrics.tags.application=${spring.application.name}
#management.tracing.enabled=false
#management.tracing.sampling.probability=1.0


# OpenTelemetry
#otel.traces.exporter=otlp
#otel.metrics.exporter=otlp
#otel.service.name=${OTEL_SERVICE_NAME}
#otel.exporter.otlp.endpoint=${OTEL_COLLECTOR_ENDPOINT}

# Spring Cloud
spring.cloud.kubernetes.discovery.enabled=true