# General
spring.config.import=optional:file:.env[.properties]

# JPA and Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.bytecode.provider=bytebuddy
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

management.endpoints.web.exposure.include=resources,*

# show full health details
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.endpoint.health.probes.enabled=true

# Eureka client configuration
spring.cloud.refresh.enabled=false
eureka.client.service-url.defaultZone=http://igrp-eureka:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=false
eureka.instance.prefer-ip-address=true