# General
spring.config.import=optional:file:.env[.properties]

server.port=${SERVICE_PORT:8080}

# Security
spring.security.user.name=admin
spring.security.user.password=admin

# JPA and Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.bytecode.provider=bytebuddy
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# Documentation
springdoc.swagger-ui.enabled=${ENABLE_SWAGGER:true}
springdoc.swagger-ui.operationsSorter=method

# Spring Cloud
spring.cloud.kubernetes.discovery.enabled=true