# General Import
spring.config.import=optional:file:.env[.properties]

# Application name
spring.application.name=iGRP-IAM
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:true}
spring.cloud.discovery.enabled=${SPRING_CLOUD_DISCOVERY_ENABLED:true}

eureka.client.enabled=${EUREKA_CLIENT_ENABLED:true}
spring.cloud.discovery.enabled=${SPRING_CLOUD_DISCOVERY_ENABLED:true}

spring.cloud.refresh.enabled=false
spring.autoconfigure.exclude=org.springframework.cloud.autoconfigure.RefreshAutoConfiguration
#spring.cloud.refresh.enabled=false
