# General
spring.config.import=optional:file:.env[.properties]

# Application name
spring.application.name=iGRP-IAM

#server.servlet.context-path=/iam

# Default profile
spring.profiles.active=${SPRING_ACTIVE_PROFILE:development}
