# General Import
spring.config.import=optional:file:.env[.properties]

server.port=${SERVICE_PORT:8080}

# Application name
spring.application.name=igrp-access-management
eureka.client.enabled=${EUREKA_CLIENT_ENABLED:false}
spring.cloud.discovery.enabled=${SPRING_CLOUD_DISCOVERY_ENABLED:false}

spring.cloud.refresh.enabled=false
spring.autoconfigure.exclude=org.springframework.cloud.autoconfigure.RefreshAutoConfiguration

springdoc.swagger-ui.docExpansion=none

# Datasource
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:postgres}}
spring.datasource.username=${DATABASE_USERNAME:${POSTGRES_USER:postgres}}
spring.datasource.password=${DATABASE_PASSWORD:${POSTGRES_PASSWORD:postgres}}
spring.datasource.driver-class-name=org.postgresql.Driver

# Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_JWT_ISSUER}

# Documentation
springdoc.swagger-ui.enabled=${ENABLE_SWAGGER:true}
springdoc.swagger-ui.operationsSorter=method

# Storage
igrp.storage-provider=${IGRP_STORAGE_PROVIDER:s3}
igrp.s3.aws-endpoint=${S3_ENDPOINT}
igrp.s3.secure=${S3_SECURITY}
igrp.s3.aws-access-key=${S3_ACCESS_KEY}
igrp.s3.aws-secret-key=${S3_SECRET_KEY}
igrp.s3.aws-bucket=${S3_BUCKET_NAME}
igrp.s3.aws-path-style-access=${S3_PATH_STYLE_ACCESS:true}
igrp.s3.aws-url-expiration-time=${S3_PRESIGNED_URL_EXPIRATION_TIME:300}
igrp.s3.aws-region=${S3_REGION:us-east-1}
debug=true

# Authentication
igrp.keycloak.server-url=${IGRP_KEYCLOAK_SERVER_URL}
igrp.keycloak.realm=${IGRP_KEYCLOAK_REALM}
igrp.keycloak.client-id=${IGRP_KEYCLOAK_CLIENT_ID}
igrp.keycloak.client-secret=${IGRP_KEYCLOAK_CLIENT_SECRET}
igrp.keycloak.grant-type=${IGRP_KEYCLOAK_GRANT_TYPE:client_credentials}

spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

# SMTP
igrp.mail.host=${SMTP_HOST:disabled}
igrp.mail.port=${SMTP_PORT:587}
igrp.mail.username=${SMTP_USERNAME:disabled}
igrp.mail.password=${SMTP_PASSWORD:disabled}
igrp.mail.properties.sender-id=${SMTP_SENDER_ID:iam@igrp.cv}

igrp.mail.invite.template=${IGRP_MAIL_INVITE_TEMPLATE:Hello {{user}}, you were successfully invited to iGRP!}

igrp.superadmin.username=${IGRP_SUPERADMIN_USERNAME:superadmin}
igrp.superadmin.email=${IGRP_SUPERADMIN_PASSWORD:superadmin@igrp.cv}