-- Step 1: Create the new table for tracking user role assignments with expiration dates
CREATE TABLE t_user_role_assignment (
    user_id INT NOT NULL,
    role_id INT NOT NULL,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_assignment_user FOREIGN KEY (user_id) REFERENCES t_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_assignment_role FOREIGN KEY (role_id) REFERENCES t_role(id) ON DELETE CASCADE
);

-- Step 2: Migrate existing data from the legacy many-to-many relationship table
-- The old table name generated by Hibernate physical naming strategy is expected to be t_role_users
-- For safety, we wrap this in a DO block to allow execution even if the table doesn't exist (e.g. fresh DB)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 't_role_users') THEN
        INSERT INTO t_user_role_assignment (user_id, role_id, assigned_at, expires_at)
        SELECT users_id as user_id, roles_id as role_id, CURRENT_TIMESTAMP, NULL
        FROM t_role_users;
        
        -- Step 3: Rename the old table as backup
        ALTER TABLE t_role_users RENAME TO t_role_users_backup;
    END IF;
END $$;
