-- Step 1: Create the new table for tracking user role assignments with expiration dates
CREATE TABLE IF NOT EXISTS t_user_role_assignment (
    user_id INT NOT NULL,
    role_id INT NOT NULL,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_assignment_user FOREIGN KEY (user_id) REFERENCES t_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_role_assignment_role FOREIGN KEY (role_id) REFERENCES t_role(id) ON DELETE CASCADE
);

-- Step 2: Migrate existing data from the legacy many-to-many relationship table
-- The old table name generated by Hibernate physical naming strategy is expected to be t_role_users
-- For safety, we wrap this in a DO block to allow execution even if the table doesn't exist (e.g. fresh DB)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 't_role_users') THEN
        INSERT INTO t_user_role_assignment (user_id, role_id, assigned_at, expires_at)
        SELECT ru.users_id as user_id, ru.roles_id as role_id, CURRENT_TIMESTAMP, NULL
        FROM t_role_users ru
        WHERE NOT EXISTS (
            SELECT 1
            FROM t_user_role_assignment ura
            WHERE ura.user_id = ru.users_id
              AND ura.role_id = ru.roles_id
        );
        
        -- Step 3: Rename the old table as backup
        IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 't_role_users_backup') THEN
            ALTER TABLE t_role_users RENAME TO t_role_users_backup;
        END IF;
    END IF;
END $$;
