name: DEV Pipeline

on:
  push:
    branches:
      - deploy/base
env:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  TARGETPLATFORMS: linux/amd64,linux/arm64

jobs:
  build-base:
    name: Build Docker Image Base Dev
    if: github.ref == 'refs/heads/deploy/base'
    runs-on: ubuntu-latest
    container:
      image: docker:28.1.1
    services:
      docker:
        image: docker:28.1.1-dind
        options: --privileged --env DOCKER_TLS_CERTDIR="" --mtu=1240
    env:
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      BASE_REGISTRY_USERNAME: ${{ secrets.BASE_REGISTRY_USERNAME }}
      BASE_REGISTRY_PASSWORD: ${{ secrets.BASE_REGISTRY_PASSWORD }}
      BASE_REGISTRY_PROJECT: ${{ secrets.BASE_REGISTRY_PROJECT }}
      CI_PIPELINE_ID: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v3

      - name: Show Docker info
        run: docker info

      - name: Register QEMU emulation
        run: docker run --privileged --rm tonistiigi/binfmt --install all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ env.BASE_REGISTRY_USERNAME }}
          password: ${{ env.BASE_REGISTRY_PASSWORD }}

      - name: Build and push multi-arch image
        run: |
          docker buildx build \
            --platform ${{ env.TARGETPLATFORMS }} \
            -t ${{ env.REGISTRY_URL }}/${{ env.BASE_REGISTRY_PROJECT }}/access-management-api:${{ env.CI_PIPELINE_ID }} \
            --push .
